name: Professions
main: me.aRt3m1s.professions.Professions
version: 0.2.0
author: ArtemisTheSecond
description: Simplified Advance Group Selection Plugin
commands:
  professions:
    description: general profession commands
    permissions: professions.cmds.all
    aliases: [p,prof,prs]
    usage: |
      §bCommand: §a/professions <parameters> [args...]
      §bShortcuts: §fuse §a/p, /prof, /pfs
      §bExample: §a/p join faction GlobalRisk §f- joins a faction GlobalRisk.
      §bExample: §a/p leave faction BlackList §f- leaves a faction BlackList.
      §bExample: §a/p list §f- list all professions.
      §bExample: §a/p list faction §f- list all groups in a profession.
      §bExample: §a/p me §f- list your groups with its profession.
      §bExample: §a/p user ArtyFowl §f- list user's groups with its profession.
      §4 /p help or /p ? - displays this.§f
  settings:
    description: configures settings.yml
    permissions: professions.settings
    aliases: [s,sett]
    usage: |
      §bCommand: §a/settings <parameters> [args...]
      §bShortcuts: §fuse §a/s, or /sett
      §bExample: §a/s addProfession faction §f- adds profession faction with default values.
      §bExample: §a/s limit faction 1 §f- sets limit to faction.
      §bExample: §a/s time faction 0 §f- sets time limit to faction.
      §bExample: §a/s joincost faction 60 §f- sets join cost to faction.
      §bExample: §a/s leavecost faction 120 §f- sets leave cost to faction.
      §bExample: §a/s iConomyEnable true §f- enables iConomy, use false to disable.
      §4 /p help §for §4/p ? - displays this.§f
permissions:
  professions.cmds.all:
    description: Enables use of all Professions commands.
    children:
      professions.cmds.join: true
      professions.cmds.leave: true
      professions.cmds.list: true
      professions.cmds.me: true
      professions.cmds.user: true
      professions.cmds.reload: true
  professions.cmds.basic:
    description: Enables use of join, leave, list, and me Professions commands.
    default: true
    children:
      professions.cmds.join: true
      professions.cmds.leave: true
      professions.cmds.list: true
      professions.cmds.me: true
  professions.cmds.advance:
    description: Enables use of join, leave, list, me, and user Professions commands.
    children:
      professions.cmds.join: true
      professions.cmds.leave: true
      professions.cmds.list: true
      professions.cmds.me: true
      professions.cmds.user: true
  professions.cmds.join:
    description: Allows use of Professions join command
    default: true
  professions.cmds.leave:
    description: Allows use of Professions leave command
    default: true
  professions.cmds.list:
    description: Allows use of Professions list command
    default: true
  professions.cmds.me:
    description: Allows use of Professions me command
    default: true
  professions.cmds.user:
    description: Allows use of Professions user command
    default: op
  professions.cmds.reload:
    description: Allows use of Professions reload command
    default: op
  professions.settings:
    description: Allows adding and manipulating settings.yml
    default: op